# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 9120d4792ca254bf419d73ab347eff67eec67d2b8059bb60edc1b6572dc2ea3c51a7a98b610463dc4673aa83878c916c1b9bf4b7e8134a289a4db668249f14c5

test:
  secret_key_base: 3eb7a8147ecc6d4d6b1eeb922097acb97ee0ac39896f4700c948fdffc49a9e24a1d3701b391ebdb40e187064a2ea14e0a3de059b836f1317fc37892ee7639c80

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
